### ISSUE TITLE
Brave search has stopped working

### ISSUE THREAD

**Issue by bestlem** [no-cmyk/Search-Engine-Spam-Blocker#5]
The latest release seems to have stopped blocking things in Brave search.

Well in some cases - the term I tried was xontrib-prompt-bar

Google and Bing do work

Looking at the[ latest commit](https://github.com/no-cmyk/Search-Engine-Spam-Blocker/commit/01804216166c8cb137525ffbe8af9e8cf15666dc) I note all files in content-scripts have been updated except brave.js

**Comment by no-cmyk** [comment]
There was a problem with the CSS selector, should be resolved now.
Thank you for the feedback.
